//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ETViewer.rc
//
#define IDC_BT_MARK_ALL                 3
#define IDC_BT_DELETE_ALL               4
#define IDD_FILTER_DIALOG_BAR           4
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDD_MAIN_DIALOG_BAR             128
#define IDR_ETViewerTYPE                129
#define IDI_PLAY                        131
#define IDD_FILTERS_EDITOR              132
#define IDD_HIGHLIGHT_FILTERS_EDITOR    133
#define IDD_FIND_DIALOG                 135
#define IDI_MARKER                      136
#define IDD_SOURCE_FILE_VIEWER          138
#define IDI_CAPTURE_START               138
#define IDD_SOURCE_FILE_CONTAINER       139
#define IDI_CAPTURE_STOP                139
#define IDI_CLEAR_EVENTS                140
#define IDD_SAVEALLTRACESQUESTIONDIALOG 140
#define IDI_CLEAR_SELECTED_EVENTS       141
#define IDD_SOURCE_FILE_VIEWER1         141
#define IDD_TRACE_DETAILS_PANE          141
#define IDI_SAVE                        142
#define IDI_SCROLL_DISABLED             143
#define IDI_COPY                        145
#define IDI_DOWN                        146
#define IDI_UP                          147
#define IDI_SCROLL_ENABLED              148
#define IDI_FILTERS                     149
#define IDI_HIGHLIGHT_FILTERS           150
#define IDI_FIND                        151
#define IDI_SHOW_HIGHLIGHT_PANEL        153
#define IDD_SETTINGS                    154
#define IDM_TRACE_LIST                  177
#define IDM_FILE_VIEWER                 178
#define IDI_SOURCE_FILE                 179
#define IDM_TRACE_LIST_EDIT             180
#define IDI_OPEN_FILE                   181
#define IDM_PROVIDER_TREE               181
#define IDM_PROVIDER_TREE1              182
#define IDM_HIGHLIGHT_FILTERS           182
#define IDI_SEQ_PLAY                    207
#define IDI_SEQ_PAUSE                   209
#define IDI_PAUSE                       209
#define IDC_LW_FILTERS                  1000
#define IDC_BT_ADD_PROVIDER             1000
#define IDC_BT_UP                       1001
#define IDC_BT_DOWN                     1002
#define IDC_BT_CLEAR_SELECTED           1003
#define IDC_BT_COPY                     1004
#define IDC_BT_SHOW_SOURCE_CONTAINER    1004
#define IDC_EDIT1                       1004
#define IDC_BT_SAVE                     1005
#define IDC_BT_FIND                     1006
#define IDC_EDIT3                       1006
#define IDC_BT_HIGHLIGHT_FILTERS        1007
#define IDC_EDIT4                       1007
#define IDC_BT_ENSURE_VISIBLE           1008
#define IDC_EDIT5                       1008
#define IDC_BT_START_STOP_CAPTURE       1009
#define IDC_EDIT6                       1009
#define IDC_EDIT11                      1010
#define IDC_BT_ERRORLOOKUP              1011
#define IDC_BUTTON1                     1011
#define IDC_BT_ADD                      1011
#define IDC_ED_ERRORLOOKUP              1012
#define IDC_EDIT7                       1012
#define IDC_BUTTON2                     1012
#define IDC_BT_REMOVE                   1012
#define IDC_EDIT8                       1013
#define IDC_LIST2                       1013
#define IDC_LW_SOURCE_PATHS             1013
#define IDC_EDIT9                       1014
#define IDC_CHECK1                      1014
#define IDC_CB_ASSOCIATE_PDB            1014
#define IDC_ST_INCLUDE_FILTER           1015
#define IDC_EDIT10                      1015
#define IDC_CHECK2                      1015
#define IDC_CB_ASSOCIATE_SOURCES        1015
#define IDC_ST_EXCLUDE_FILTER           1016
#define IDC_CHECK3                      1016
#define IDC_CB_ASSOCIATE_ETL            1016
#define IDC_EDIT2                       1018
#define IDC_CB_INCLUDE_FILTER           1019
#define IDC_BUTTON3                     1019
#define IDC_BT_SELECT_FONT              1019
#define IDC_CB_EXCLUDE_FILTER           1020
#define IDC_ST_FONT_FAMILY              1023
#define IDI_ETL_ICON                    1024
#define IDC_RB_PDB_RELOAD_AUTO          1024
#define IDC_RB_PDB_RELOAD_ASK           1025
#define IDC_RB_PDB_RELOAD_DISABLED      1026
#define IDC_RB_SOURCE_RELOAD_AUTO       1027
#define IDC_RB_SOURCE_RELOAD_ASK        1028
#define IDC_RADIO6                      1029
#define IDC_RB_SOURCE_RELOAD_DISABLED   1029
#define IDC_BT_CLEAR                    1031
#define IDC_CB_FIND_PID_NAME            1042
#define IDC_CB_FIND_IN_TRACE_TEXT       1043
#define IDC_ED_FILE                     1048
#define IDC_TC_SOURCE_FILES             1049
#define IDC_BT_CLOSE_FILE               1051
#define IDC_ED_FULL_PATH                1053
#define IDC_ED_LINE                     1054
#define IDC_BT_OPEN_FILE                1055
#define IDC_CO_TEXT_TO_FIND             1067
#define IDC_BT_RECENT_FILE              1068
#define IDC_BT_SELECTED                 1069
#define IDI_ERRORLOOKUP                 32513
#define IDI_HOLLOW                      32514
#define IDI_CLOSE_SMALL                 32515
#define IDI_HOLLOW_BIG                  32528
#define IDI_LEVEL                       32529
#define IDI_FLAGS                       32530
#define IDI_CHECKED                     32531
#define IDI_UNCHECKED                   32532
#define IDI_CHECKED2                    32533
#define IDI_SELECTED                    32533
#define IDI_SHOW_HIGHLIGHT_PANEL1       32534
#define IDI_SHOW_HIGHLIGHT_PANEL2       32535
#define IDI_PLAY_BLOCKED                32536
#define IDI_RECORD                      32537
#define IDR_MAINFRAME1                  32538
#define ID_BUTTON32771                  32771
#define ID_BUTTON32773                  32773
#define ID_BUTTON32774                  32774
#define ID_OPEN_AS_SOURCE_FILE          32775
#define ID_CLEAR                        32776
#define ID_COPY                         32778
#define ID_SELECT_ALL                   32779
#define ID_TRACE_LIST_CLEAR             32779
#define ID_EXECUTE                      32781
#define ID_TRACE_LIST_COPY              32781
#define ID_GET_ERROR_DESCRIPTION        32782
#define ID_TRACE_LIST_OPEN_SOURCE_FILE  32782
#define ID_232131_COLUMNS               32783
#define ID_COLUMNS_                     32784
#define ID_TRACE_LIST_COPY_SELECTION    32785
#define ID_TRACE_LIST_COPY_ALL          32786
#define ID_TRACE_LIST_DELETE_SELECTION  32787
#define ID_TRACE_LIST_DELETE_ALL        32788
#define ID_232131_LEVEL                 32789
#define ID_PROVIDER_TREE_ALL_FATAL      32797
#define ID_PROVIDER_TREE_ALL_ERROR      32798
#define ID_PROVIDER_TREE_ALL_WARNING    32799
#define ID_PROVIDER_TREE_ALL_INFORMATION 32800
#define ID_PROVIDER_TREE_ALL_VERBOSE    32801
#define ID_PROVIDER_TREE_ALL_RESERVED6  32802
#define ID_PROVIDER_TREE_ALL_RESERVED7  32803
#define ID_PROVIDER_TREE_ALL_RESERVED8  32804
#define ID_PROVIDER_TREE_ALL_RESERVED9  32805
#define ID_PROVIDER_TREE_DELETE_PROVIDER 32806
#define ID_PROVIDER_TREE_DELETE_ALL_PROVIDERS 32807
#define ID_PROVIDER_TREE_ADD_PROVIDER   32812
#define ID_232131_ALLPROVIDERS          32813
#define ID_ALLPROVIDERS_FLAGS           32814
#define ID_ALLPROVIDERS_FLAGS32815      32815
#define ID_PROVIDER_TREE_START_ALL      32816
#define ID_PROVIDER_TREE_STOP_ALL       32817
#define ID_PROVIDER_TREE_SET_ALL_FLAGS_ALL 32818
#define ID_PROVIDER_TREE_CLEAR_ALL_FLAGS_ALL 32819
#define ID_PROVIDER_TREE_START          32820
#define ID_HIGHLIGHT_FILTERS_ADD        32820
#define ID_PROVIDER_TREE_STOP           32821
#define ID_HIGHLIGHT_FILTERS_DELETE     32821
#define ID_PROVIDER_TREE_SET_ALL_FLAGS  32822
#define ID_PROVIDER_TREE_CLEAR_ALL_FLAGS 32823
#define ID_HIGHLIGHT_FILTERS_DOWN       32825
#define ID_HIGHLIGHT_FILTERS_UP         32826
#define ID_TRACES_FONT                  32826
#define ID_FONT_SMALLER                 32827
#define ID_FONT_BIGGER                  32828
#define ID_FILE_RECENT_PDBS             32831
#define ID_FILE_RECENT_SOURCES          32832
#define ID_RECENTPDBS_                  32833
#define ID_RECENTSOURCES_               32834
#define ID_FILE_RECENTLOGS              32835
#define ID_RECENTLOGS_                  32836
#define ID_FILE_CLOSELOG                32837
#define ID_FILE_STOPLOGGINTOFILE        32839
#define ID_EDIT_SETTINGS                32840
#define ID_PROVIDER_TREE_RELOAD_PROVIDER 32842
#define ID_PROVIDER_TREE_RELOAD_ALL_PROVIDERS 32845
#define ID_FILE_LOGTOFILE               32846
#define IDI_MODULE                      32847

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
